/********************************************************************
* SclassDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error SclassDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableSclassDict();
extern void G__cpp_setup_inheritanceSclassDict();
extern void G__cpp_setup_typetableSclassDict();
extern void G__cpp_setup_memvarSclassDict();
extern void G__cpp_setup_globalSclassDict();
extern void G__cpp_setup_memfuncSclassDict();
extern void G__cpp_setup_funcSclassDict();
extern void G__set_cpp_environmentSclassDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Sclass.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__SclassDictLN_TClass;
extern G__linked_taginfo G__SclassDictLN_TBuffer;
extern G__linked_taginfo G__SclassDictLN_TMemberInspector;
extern G__linked_taginfo G__SclassDictLN_TObject;
extern G__linked_taginfo G__SclassDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__SclassDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SclassDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__SclassDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SclassDictLN_Sclass;

/* STUB derived class for protected member access */
